### ISSUE TITLE
iOS 连接 OneKey 之后不能获取账户

### ISSUE THREAD

**Issue by EnnnOK** [OneKeyHQ/ios-app-legacy#4]
iOS 连接到 OneKey 之后，使用 BTC 恢复账户，进入恢复账户页面之后报错 `Excepted Point, got a` 后面的信息看不到了，然后回到恢复账户的页面。

直接 USB 连接到 Windows 上之后可以获取到账户。

iOS 的 APP 是用台湾账号下载的，开发者是 `ONEKEY LIMITED`，版本是 `1.2.0-20220530063`。

OneKey 的固件版本是和蓝牙固件版本都已经更新了，固件版本 2.2.0，蓝牙版本 1.2.1。

麻烦修复下。

**Comment by rayston92** [comment]
@EnnnOK 

这个 App 是全新构建的 App，并非 Legacy。不过没有关系，在这里提 issue 也是可以的。

已经看到上述信息，正在查看原因。

cc @loatheb @taimanhui

**Comment by EnnnOK** [comment]
OK /close
